#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 30 19:27:47 2019

@author: artsin
"""

import argparse

parser = argparse.ArgumentParser(description='Process some integers.')
parser.add_argument('hexvalue', metavar='N', type=lambda x: int(x,0), nargs='+',
                    help='HEX value to display')

args = parser.parse_args()
binstring = bin(args.hexvalue[0]).split('b')[1]
binstring = binstring[::-1]
print("Num\t:\tVal")
print("====================")
for index, value in enumerate(binstring):
    print(index, "\t:\t", value)
    print("--------------------")
